### ISSUE TITLE
Bound time check doesn't take into consideration time loading private key

### ISSUE THREAD

**Issue by PhilipSkinner** [alphagov/notifications-api#3899]
I have noticed a sporadic issue when we get back a clock skew error that does not appear to be related to our clock time.

I believe the issue is that the time taken from receiving the request to decoding and validating the jwt (using the `__bound__` value) isn't taken into consideration - and there is a database operation in between these things.

I believe the fix is to take a note of the time at the start of [`requires_auth`](https://github.com/alphagov/notifications-api/blob/c01a9109a89bcf272dd0d85cd5d6dce78f1c4597/app/authentication/auth.py#L91) which can then be passed into [`_decode_jwt_token`](https://github.com/alphagov/notifications-api/blob/c01a9109a89bcf272dd0d85cd5d6dce78f1c4597/app/authentication/auth.py#L114) before then being passed into [`decode_jwt_token`](https://github.com/alphagov/notifications-api/blob/c01a9109a89bcf272dd0d85cd5d6dce78f1c4597/app/authentication/auth.py#L132) so it can then be taken into account when calculating the [leeway](https://github.com/alphagov/notifications-python-client/blob/c40bb2d777cc4eefa66c10b5de8832bd46e97b63/notifications_python_client/authentication.py#L104) on date/time validation.

**Comment by leohemsted** [comment]
Hi Philip,

Thanks for bringing this up - we discussed this internally a couple of times, and have had a look at the logs to diagnose why you're sometimes seeing these sporadic clock skew errors.

So firstly of note, these errors you're seeing are incredibly low - in the last two weeks we're talking 8 from 32 million. That's an 8-nines level of uptime. This doesn't excuse them, but ultimately there will always be some risk of network infrastructure causing these errors. 

Out of the errors, we can broadly split them into two categories:

### System Clock errors where the request time is quick

We can tell from our logs that some of these requests were quick to return - When we first investigated last week we saw several with response times (measured within our infrastructure at the load balancer layer) of 0.015, 0.016, 0.018, 0.021 seconds. If we're ruling out either server or client clock drift, then the other conclusion is that somewhere in the network between (which feels likely given the very low volume of errors). Ultimately I think this can just fall under [fallacies of distributed computing](https://en.wikipedia.org/wiki/Fallacies_of_distributed_computing) as an inevitability that can never be 100% mitigated. I hope it's clear that within this, moving a timestamp a few milliseconds forward or back wouldn't be able to solve those issues.

### System Clock errors where the request time is slow

On the other hand, some of these requests (specifically those around lunchtime on October 10th) _did_ take a long time. They were often returning in 32 seconds or so. This was during a period of particularly high load when we were seeing many requests take a long period of time, including us seeing some database connections time out (our API is configured so any request will timeout if it cannot acquire a database connection within 30 seconds).

Your proposal would ensure that your JWT tokens were validated successfully, which would result in a successful but potentially incredibly long-running request. If users (or intermediary hops) have timeouts configured, this may result in a notification being created but not being fed back to the user, leading to confusion and potential for duplication.

However, I think there's a more philosophical question for us at Notify team to consider. I'm struggling to articulate, but basically, rather than us spend time solving “we need to make authentication resilient against taking 30 seconds to get a DB connection”, I'd rather Notify didn't take 30 seconds to acquire a DB connection. And if we are taking that long, I'd rather we can recognise that and return a 5xx error code because clearly our API is not behaving in a healthy manner.

-----

Anyway, I've rambled on a bit.

We're pretty busy so unfortunately we won't be able to support implementing and deploying a change like this at the moment - however I am keen to take a look at our API user experience at some point in the medium-term future, and this would likely involve looking at our clients and how they authenticate, but in a more wholesale and joined up approach that considers all the benefits and issues from our current approach of short-lived JWT tokens. I know we've chatted on x-gov slack about idempotency tokens too.

For now, I think I'd have to suggest that in the event of specifically a system clock related 403 error, you could consider retrying the notification. We'll keep an eye on these errors and if they start rising we may consider other approaches.

Cheers for raising the issue! It's spurred a lot of useful and constructive conversation within our team.

**Comment by PhilipSkinner** [comment]
What an excellent reply!

The fast failures are interesting, unfortunately I don't think we capture any network egress statistics so we many never know what caused those fast calls to fail.

I completely agree on the "this shouldn't happen, lets fix the underlying issue". We have implemented a retry mechanism that specifically does a simple retry over the 403 requests already - returning a 5xx series response code would be more semantically correct - a 503 would be nice as that would allow us to understand we need to back off for a while.

I worry that a dumb retry could cause extra load on your system when its already under heavy load, making things worse - we are planning on making improvements here to be a good API consumer.

I'll feed this back to our architect/tech leads.
